---

#language: python
#python: "2.7"
sudo: required

env:
  - distro: centos7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distro: ubuntu1604
    init: /lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

services:
  - docker

before_install:
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:
  - container_id=$(mktemp)
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} geerlingguy/docker-${distro}-ansible:latest "${init}" > "${container_id}"'
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm
    ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check
#  - >
#    docker exec --tty "$(cat ${container_id})" env TERM=xterm
#    ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
#  - idempotence=$(mktemp)
#  - >
#    docker exec --tty "$(cat ${container_id})"
#    ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
#    | tee -a ${idempotence}
#  - >
#    tail ${idempotence}
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)
#  - curl https://localhost:32400/web

