---

##
## File: install-Debian.yml
##

- name: Ubuntu | add repository key
  become: True
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Ubuntu | add repository
  become: True
  apt_repository:
    state: present
    repo: deb https://downloads.plex.tv/repo/deb public main
    filename: 'plexmediaserver'
    update_cache: yes

- name: Ubuntu | install plex media server
  become: True
  apt:
    name: plexmediaserver
    state: "{{ plex_version }}"
  notify: restart-plex-server
