---

##
## File: main.yml
##

- block:
  - import_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian'

- block:
  - import_tasks: install-RedHat.yml
  - import_tasks: setup-firewalld.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-services.yml
