---

##
## File: main.yml
##

- import_tasks: install-RedHat.yml
  when: ansible_os_family =='RedHat'

- import_tasks: firewall-RedHat.yml
  when: ansible_os_family =='RedHat'

- import_tasks: services.yml
