---

##
## File: main.yml
##

- block:
  - import_tasks: install-Debian.yml
  when: ansible_os_family =='Debian'

- block:
  - import_tasks: install-RedHat.yml
  - import_tasks: firewall-RedHat.yml
  when: ansible_os_family =='RedHat'

- import_tasks: services.yml
