---

##
## File: firewall-RedHat.yml
##

- name: PLEX | firewall (web access)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: "{{ plex_port }}/tcp"

- name: PLEX | firewall (DLNA Server)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: "{{ item }}"
  with_items:
  - 1900/udp
  - 32469/tcp

- name: PLEX | firewall (Companion)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: 3005/tcp

- name: PLEX | firewall (Roku)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: 8324/tcp

- name: PLEX | firewall (Legacy Bonjour/Avahi Discovery)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: 5353/udp

- name: PLEX | firewall (GDM Network Discovery)
  become: True
  firewalld:
    state: enabled
    immediate: yes
    permanent: yes
    port: "{{ item }}"
  with_items:
  - 32410/udp
  - 32412/udp
  - 32413/udp
  - 32414/udp

